{% set name = "opensearch-py" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c09a73727868c29f86ffbed1e987afb7f86bcce983b28bf69249cfad8c831d68

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6,<4.0
    - pip
  run:
    - python >=3.6,<4.0
    - urllib3 >=1.26.18,<2
    - requests >=2.4.0,<3.0.0
    - six
    - python-dateutil
    - certifi >=2022.12.07

test:
  imports:
    - opensearchpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/opensearch-project/opensearch-py
  summary: Python low-level client for OpenSearch
  doc_url: https://opensearch.org/docs/latest/clients/python/
  dev_url: https://github.com/opensearch-project/opensearch-py
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - chrisburr
